version: '3.8'
services:
    mqttserver:
        image: "eclipse-mosquitto:2.0.15"
        container_name: mqttserver
        restart: unless-stopped
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - iot_net
        volumes:
            - mosquitto_data:/mosquitto/data
            - mosquitto_log:/mosquitto/log
            - mosquitto_config:/mosquitto/config
    openhab:
        image: "openhab/openhab:3.4.3"
        container_name: openhab
        restart: unless-stopped
        ports:
            - "8080:8080"
            - "8443:8443"
        networks:
            - iot_net
        depends_on:
            - mqttserver
        volumes:
            - openhab_data:/openhab/userdata
            - openhab_conf:/openhab/conf
            - openhab_addons:/openhab/addons
        environment:
            - OPENHAB_HTTP_PORT=8080
            - OPENHAB_HTTPS_PORT=8443
            - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin

volumes:
    openhab_data:
    openhab_conf:
    openhab_addons:
    mosquitto_data:
    mosquitto_log:
    mosquitto_config:

networks:
    iot_net: